version: '3.8'
services:
  api:
    image: YOUR_DOCKER_IMAGE
    environment:
      - OPENAI_API_KEY
      - MAILGUN_API_KEY
      - GARMIN_SUMMARY_DB_PATH
      - TO_EMAIL
      - FROM_EMAIL
      - FROM_EMAIL_DOMAIN
    ports:
      - '8001:8001'
    networks:
      - default
    volumes:
      - /path/to/your/garmin/data:/data

networks:
  default:
    driver: bridge
